### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by ghost** [N0rz3/Vinted-webhook#1]
quand je lance le script il y a tout le temps une ratelimit sauf et en ajoutant `Exception as e ` et en affichant le cpde d'erreure est bien c'etait un code 403

**Comment by N0rz3** [comment]
salut alors pour l'instant je ne comprend pas trop pourquoi sa le fait (pas qu'à toi) mais sa reste bizarre car moi cela fonctionne correctement
